version: "3.7"
services:
  mongodb:
    # Сервис MongoDB
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGODB_DATABASE: reminder
      MONGODB_HOSTNAME: mongodb
      TELEGRAM_TOKEN: "YOUR TOCUN TELEGRAM"
    ports:
      - 127.0.0.1:24000:27020
    volumes:
      - mongodb_data:/data/db

  reminder_bot:
    # reminder_bot
    platform: linux/amd64
    build: .
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGODB_DATABASE: reminder
      MONGODB_HOSTNAME: mongodb
      TELEGRAM_TOKEN: "YOUR TOCUN TELEGRAM"
    volumes:
      - ./app:/home/nonroot/app
    command: sh -c "ulimit -n 1024 && poetry run watchmedo auto-restart -d . -p '*.py' -R -- python3 bot/__init__.py"

    depends_on:
      - mongodb

volumes:
  mongodb_data:
